---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nhhon5mp/thon09.hongphongnb.com/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/storage $DEPLOYPATH/uploads $DEPLOYPATH/backups $DEPLOYPATH/cache $DEPLOYPATH/sessions $DEPLOYPATH/logs
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp manifest.json $DEPLOYPATH
    - /bin/cp manifest.webmanifest $DEPLOYPATH
    - /bin/cp offline.html $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp service-worker.js $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp -R api $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R sample-data $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R controllers $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R install $DEPLOYPATH
    - /bin/cp -R models $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp -R views $DEPLOYPATH
    - export DEPLOYPATH=/home/nhhon5mp/thon10.hongphongnb.com/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/storage $DEPLOYPATH/uploads $DEPLOYPATH/backups $DEPLOYPATH/cache $DEPLOYPATH/sessions $DEPLOYPATH/logs
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp manifest.json $DEPLOYPATH
    - /bin/cp manifest.webmanifest $DEPLOYPATH
    - /bin/cp offline.html $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp service-worker.js $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp -R api $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R sample-data $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R controllers $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R install $DEPLOYPATH
    - /bin/cp -R models $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp -R views $DEPLOYPATH
