const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const conversation = fs.readFileSync(path.join(root, 'assets/js/ai-conversation.js'), 'utf8');
const appCss = fs.readFileSync(path.join(root, 'assets/css/app.css'), 'utf8');
const appView = fs.readFileSync(path.join(root, 'views/app.php'), 'utf8');
const buildAssets = fs.readFileSync(path.join(root, 'tools/build-assets.js'), 'utf8');

assert.match(conversation, /TenantAiConversation/);
assert.match(conversation, /tenant:ai-intent-recognized/);
assert.match(conversation, /tenant:ai-conversation-clarification/);
assert.match(conversation, /\/api\/ai\/ask/);
assert.match(conversation, /tenant:ai-answer/);
assert.match(conversation, /TenantAiConversation = Object\.freeze/);
assert.match(conversation, /ask: askBackend/);
assert.match(conversation, /appendResultPreview/);
assert.match(conversation, /appendSourceLine/);
assert.match(conversation, /sourceText/);
assert.match(conversation, /ai-source-line/);
assert.match(conversation, /Nguon: /);
assert.match(conversation, /ai-result-preview/);
assert.match(conversation, /previewRows/);
assert.match(conversation, /plan\.tool === 'insight'/);
assert.match(conversation, /source\.metrics/);
assert.match(conversation, /metric /);
assert.match(conversation, /setAskBusy/);
assert.match(conversation, /aria-busy/);
assert.match(conversation, /fa-spinner fa-spin/);
assert.match(conversation, /Đang xử lý/);
assert.match(conversation, /Đang trả lời/);
assert.match(conversation, /#aiAskBtn/);
assert.match(conversation, /userAlreadyAdded/);
assert.match(conversation, /localStorage/);
assert.match(conversation, /maxMessages = 20/);
assert.match(conversation, /typeof window\.api === 'function'/);
assert.match(conversation, /X-CSRF-Token/);
assert.match(conversation, /\bfetch\s*\(path/);
assert.doesNotMatch(conversation, /XMLHttpRequest/);
assert.doesNotMatch(conversation, /TenantAppPlatform\.actions/);
assert.doesNotMatch(conversation, /data-platform-action/);
assert.doesNotMatch(conversation, /location\.(href|assign|replace)/);

assert.match(appView, /id="aiConversationLog"/);
assert.match(appView, /id="aiConversationClearBtn"/);
assert.match(appView, /src="\/assets\/js\/ai-conversation\.min\.js\?v=20260726-ai-ui-2"/);
assert.match(appView, /id="aiAskBtn"/);
assert.match(appCss, /\.ai-result-preview/);
assert.match(appCss, /\.ai-source-line/);
assert.match(appCss, /\.ai-result-row/);
assert.match(buildAssets, /assets\/js\/ai-conversation\.js/);

console.log('AI conversation checks passed');
