CREATE TABLE IF NOT EXISTS public_asset_inventory_groups (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(180) NOT NULL,
  parent_name VARCHAR(180) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_public_asset_inventory_groups_name (name),
  KEY idx_public_asset_inventory_groups_active (is_active),
  KEY idx_public_asset_inventory_groups_parent (parent_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS public_asset_inventory_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_asset_id BIGINT UNSIGNED NOT NULL,
  inventory_code VARCHAR(60) NOT NULL,
  item_name VARCHAR(255) NOT NULL,
  group_id BIGINT UNSIGNED NULL,
  group_name VARCHAR(180) NULL,
  quantity DECIMAL(14,2) NOT NULL DEFAULT 1,
  unit VARCHAR(80) NULL,
  condition_status ENUM('GOOD','IN_USE','LIGHT_DAMAGE','HEAVY_DAMAGE','NEEDS_REPAIR','LIQUIDATED','DELETED') NOT NULL DEFAULT 'IN_USE',
  start_use_date DATE NULL,
  location_in_asset VARCHAR(255) NULL,
  note TEXT NULL,
  photo_url VARCHAR(500) NULL,
  status ENUM('ACTIVE','DELETED') NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  deleted_at DATETIME NULL,
  deleted_by BIGINT UNSIGNED NULL,
  UNIQUE KEY uq_public_asset_inventory_code (inventory_code),
  KEY idx_public_asset_inventory_asset (public_asset_id),
  KEY idx_public_asset_inventory_group (group_id),
  KEY idx_public_asset_inventory_condition (condition_status),
  KEY idx_public_asset_inventory_status (status),
  CONSTRAINT fk_public_asset_inventory_asset FOREIGN KEY (public_asset_id) REFERENCES public_assets(id) ON DELETE CASCADE,
  CONSTRAINT fk_public_asset_inventory_group FOREIGN KEY (group_id) REFERENCES public_asset_inventory_groups(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO public_asset_inventory_groups (name, parent_name, sort_order) VALUES
('Nội thất','Nội thất',10),
('Bàn','Nội thất',20),
('Ghế','Nội thất',30),
('Tủ','Nội thất',40),
('Kệ','Nội thất',50),
('Thiết bị điện','Thiết bị điện',60),
('Quạt','Thiết bị điện',70),
('Điều hòa','Thiết bị điện',80),
('Đèn','Thiết bị điện',90),
('Bình nóng lạnh','Thiết bị điện',100),
('Điện tử','Điện tử',110),
('Máy tính','Điện tử',120),
('Máy in','Điện tử',130),
('Máy chiếu','Điện tử',140),
('Loa','Điện tử',150),
('Amply','Điện tử',160),
('Micro','Điện tử',170),
('Camera','Điện tử',180),
('PCCC','PCCC',190),
('Bình chữa cháy','PCCC',200),
('Tủ PCCC','PCCC',210),
('Chuông báo cháy','PCCC',220),
('Thiết bị khác','Thiết bị khác',230),
('Dụng cụ vệ sinh','Thiết bị khác',240),
('Thiết bị thể thao','Thiết bị khác',250),
('Thiết bị y tế','Thiết bị khác',260),
('Thiết bị văn phòng','Thiết bị khác',270)
ON DUPLICATE KEY UPDATE parent_name=VALUES(parent_name), sort_order=VALUES(sort_order), is_active=1;
