-- Additive migration: Quoc phong - An ninh module.
CREATE TABLE IF NOT EXISTS defense_security_settings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  village_id BIGINT UNSIGNED NOT NULL,
  setting_key VARCHAR(80) NOT NULL,
  setting_value VARCHAR(255) NOT NULL,
  applied_year INT NULL,
  note VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_defense_setting (village_id, setting_key, applied_year),
  KEY idx_defense_setting_village (village_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS defense_nvqs_records (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  village_id BIGINT UNSIGNED NOT NULL,
  citizen_id BIGINT UNSIGNED NOT NULL,
  recruitment_year INT NOT NULL,
  registered_status ENUM('YES','NO') NOT NULL DEFAULT 'NO',
  registration_date DATE NULL,
  preliminary_status ENUM('NOT_UPDATED','PENDING','PASSED','FAILED') NOT NULL DEFAULT 'NOT_UPDATED',
  preliminary_date DATE NULL,
  medical_exam_status ENUM('NOT_UPDATED','PENDING','PASSED','FAILED') NOT NULL DEFAULT 'NOT_UPDATED',
  medical_exam_date DATE NULL,
  health_classification VARCHAR(80) NULL,
  eligibility_status ENUM('UNKNOWN','ELIGIBLE','INELIGIBLE','DEFERRED','EXEMPT') NOT NULL DEFAULT 'UNKNOWN',
  deferment_reason VARCHAR(255) NULL,
  exemption_reason VARCHAR(255) NULL,
  selection_status ENUM('NOT_SELECTED','SELECTED','ENLISTED') NOT NULL DEFAULT 'NOT_SELECTED',
  order_received TINYINT(1) NOT NULL DEFAULT 0,
  enlistment_date DATE NULL,
  enlistment_unit VARCHAR(255) NULL,
  active_service TINYINT(1) NOT NULL DEFAULT 0,
  discharge_date DATE NULL,
  discharge_unit VARCHAR(255) NULL,
  completed_service TINYINT(1) NOT NULL DEFAULT 0,
  status ENUM('ACTIVE','DELETED') NOT NULL DEFAULT 'ACTIVE',
  note TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  deleted_at DATETIME NULL,
  deleted_by BIGINT UNSIGNED NULL,
  UNIQUE KEY uq_defense_nvqs_year (village_id, citizen_id, recruitment_year),
  KEY idx_defense_nvqs_citizen (citizen_id),
  KEY idx_defense_nvqs_year (village_id, recruitment_year),
  CONSTRAINT fk_defense_nvqs_citizen FOREIGN KEY (citizen_id) REFERENCES citizens(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS defense_militia_records (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  village_id BIGINT UNSIGNED NOT NULL,
  citizen_id BIGINT UNSIGNED NOT NULL,
  militia_type ENUM('CORE','MOBILE','ON_SITE','SPECIALIZED','OTHER') NOT NULL DEFAULT 'CORE',
  position_name VARCHAR(120) NULL,
  unit_name VARCHAR(255) NULL,
  joined_date DATE NULL,
  ended_date DATE NULL,
  training_name VARCHAR(255) NULL,
  training_date DATE NULL,
  training_result VARCHAR(255) NULL,
  participation_status ENUM('ACTIVE','PAUSED','COMPLETED','ENDED') NOT NULL DEFAULT 'ACTIVE',
  reason VARCHAR(255) NULL,
  note TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  deleted_at DATETIME NULL,
  deleted_by BIGINT UNSIGNED NULL,
  status ENUM('ACTIVE','DELETED') NOT NULL DEFAULT 'ACTIVE',
  KEY idx_defense_militia_village (village_id),
  KEY idx_defense_militia_citizen (citizen_id),
  CONSTRAINT fk_defense_militia_citizen FOREIGN KEY (citizen_id) REFERENCES citizens(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS defense_security_force_records (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  village_id BIGINT UNSIGNED NOT NULL,
  citizen_id BIGINT UNSIGNED NOT NULL,
  team_name VARCHAR(255) NOT NULL,
  position_code ENUM('LEADER','DEPUTY','MEMBER') NOT NULL DEFAULT 'MEMBER',
  joined_date DATE NULL,
  ended_date DATE NULL,
  area_in_charge VARCHAR(255) NULL,
  participation_status ENUM('ACTIVE','PAUSED','ENDED') NOT NULL DEFAULT 'ACTIVE',
  reason VARCHAR(255) NULL,
  note TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  deleted_at DATETIME NULL,
  deleted_by BIGINT UNSIGNED NULL,
  status ENUM('ACTIVE','DELETED') NOT NULL DEFAULT 'ACTIVE',
  KEY idx_defense_security_force_village (village_id),
  KEY idx_defense_security_force_citizen (citizen_id),
  KEY idx_defense_security_force_team (village_id, team_name),
  CONSTRAINT fk_defense_security_force_citizen FOREIGN KEY (citizen_id) REFERENCES citizens(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
