CREATE TABLE IF NOT EXISTS photo_gallery_albums (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  album_code VARCHAR(60) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  description TEXT NULL,
  cover_item_id BIGINT UNSIGNED NULL,
  status ENUM('ACTIVE','ARCHIVED','DELETED') NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  deleted_at DATETIME NULL,
  deleted_by BIGINT UNSIGNED NULL,
  KEY idx_photo_gallery_albums_status (status),
  KEY idx_photo_gallery_albums_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS photo_gallery_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  album_id BIGINT UNSIGNED NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  original_name VARCHAR(255) NOT NULL,
  stored_name VARCHAR(255) NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  mime_type VARCHAR(120) NOT NULL,
  file_size BIGINT UNSIGNED NOT NULL DEFAULT 0,
  taken_at DATETIME NULL,
  event_date DATE NULL,
  area_code VARCHAR(80) NULL,
  source_module VARCHAR(80) NULL,
  source_id BIGINT UNSIGNED NULL,
  tags_text VARCHAR(500) NULL,
  status ENUM('ACTIVE','DELETED') NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  deleted_at DATETIME NULL,
  deleted_by BIGINT UNSIGNED NULL,
  KEY idx_photo_gallery_items_album (album_id),
  KEY idx_photo_gallery_items_status (status),
  KEY idx_photo_gallery_items_event_date (event_date),
  KEY idx_photo_gallery_items_area (area_code),
  KEY idx_photo_gallery_items_source (source_module, source_id),
  FULLTEXT KEY ft_photo_gallery_items_search (title, description, original_name, tags_text),
  CONSTRAINT fk_photo_gallery_items_album FOREIGN KEY (album_id) REFERENCES photo_gallery_albums(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
