CREATE TABLE IF NOT EXISTS livestock (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  household_id BIGINT UNSIGNED NOT NULL,
  animal_type VARCHAR(80) NOT NULL,
  breed VARCHAR(120) NULL,
  quantity INT UNSIGNED NOT NULL DEFAULT 0,
  vaccinated TINYINT(1) NOT NULL DEFAULT 0,
  vaccine_date DATE NULL,
  disease_status ENUM('NONE','SUSPECTED','INFECTED','RECOVERED') NOT NULL DEFAULT 'NONE',
  barn_area VARCHAR(255) NULL,
  status ENUM('ACTIVE','INACTIVE','DELETED') NOT NULL DEFAULT 'ACTIVE',
  note TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  deleted_at DATETIME NULL,
  deleted_by BIGINT UNSIGNED NULL,
  KEY idx_livestock_household (household_id),
  KEY idx_livestock_animal_type (animal_type),
  KEY idx_livestock_status (status),
  KEY idx_livestock_vaccinated (vaccinated),
  CONSTRAINT fk_livestock_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
