CREATE TABLE IF NOT EXISTS `household_business` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `household_id` BIGINT UNSIGNED NOT NULL,
  `business_type` ENUM('RESIDENT','PRODUCTION','BUSINESS','BOTH') NOT NULL DEFAULT 'RESIDENT',
  `business_name` VARCHAR(255) NULL,
  `owner_name` VARCHAR(255) NULL,
  `production_sector` VARCHAR(255) NULL,
  `business_sector` VARCHAR(255) NULL,
  `business_license` VARCHAR(100) NULL,
  `license_date` DATE NULL,
  `license_place` VARCHAR(255) NULL,
  `tax_code` VARCHAR(50) NULL,
  `start_date` DATE NULL,
  `worker_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `annual_revenue` DECIMAL(18,2) NULL,
  `phone` VARCHAR(30) NULL,
  `email` VARCHAR(150) NULL,
  `address` VARCHAR(500) NULL,
  `latitude` DECIMAL(10,8) NULL,
  `longitude` DECIMAL(11,8) NULL,
  `status` ENUM('ACTIVE','INACTIVE','SUSPENDED','DELETED') NOT NULL DEFAULT 'ACTIVE',
  `note` TEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  `deleted_at` DATETIME NULL,
  `deleted_by` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_household_business_household` (`household_id`),
  KEY `idx_household_business_type` (`business_type`),
  KEY `idx_household_business_status` (`status`),
  KEY `idx_household_business_sector` (`production_sector`, `business_sector`),
  KEY `idx_household_business_license` (`business_license`),
  KEY `idx_household_business_tax` (`tax_code`),
  KEY `idx_household_business_location` (`latitude`, `longitude`),
  CONSTRAINT `fk_household_business_household` FOREIGN KEY (`household_id`) REFERENCES `households` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_household_business_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_household_business_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_household_business_deleted_by` FOREIGN KEY (`deleted_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `permissions` (`role`, `module`, `action`, `allowed`)
VALUES
('ADMIN','household_business','read',1),
('ADMIN','household_business','create',1),
('ADMIN','household_business','update',1),
('ADMIN','household_business','delete',1),
('OFFICER','household_business','read',1),
('OFFICER','household_business','create',1),
('OFFICER','household_business','update',1),
('VIEWER','household_business','read',1)
ON DUPLICATE KEY UPDATE `allowed` = VALUES(`allowed`);
