CREATE TABLE IF NOT EXISTS public_asset_inventory_groups (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(180) NOT NULL,
  parent_name VARCHAR(180) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_public_asset_inventory_groups_name (name),
  KEY idx_public_asset_inventory_groups_active (is_active),
  KEY idx_public_asset_inventory_groups_parent (parent_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS public_asset_inventory_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_asset_id BIGINT UNSIGNED NOT NULL,
  inventory_code VARCHAR(60) NOT NULL,
  item_name VARCHAR(255) NOT NULL,
  group_id BIGINT UNSIGNED NULL,
  group_name VARCHAR(180) NULL,
  quantity DECIMAL(14,2) NOT NULL DEFAULT 1,
  unit VARCHAR(80) NULL,
  condition_status ENUM('NEW','GOOD','IN_USE','MAINTENANCE','LIGHT_DAMAGE','HEAVY_DAMAGE','NEEDS_REPAIR','LIQUIDATED','DELETED') NOT NULL DEFAULT 'IN_USE',
  start_use_date DATE NULL,
  location_in_asset VARCHAR(255) NULL,
  note TEXT NULL,
  photo_url VARCHAR(500) NULL,
  status ENUM('ACTIVE','DELETED') NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  deleted_at DATETIME NULL,
  deleted_by BIGINT UNSIGNED NULL,
  UNIQUE KEY uq_public_asset_inventory_code (inventory_code),
  KEY idx_public_asset_inventory_asset (public_asset_id),
  KEY idx_public_asset_inventory_group (group_id),
  KEY idx_public_asset_inventory_condition (condition_status),
  KEY idx_public_asset_inventory_status (status),
  CONSTRAINT fk_public_asset_inventory_asset FOREIGN KEY (public_asset_id) REFERENCES public_assets(id) ON DELETE CASCADE,
  CONSTRAINT fk_public_asset_inventory_group FOREIGN KEY (group_id) REFERENCES public_asset_inventory_groups(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO public_asset_inventory_groups (name, parent_name, sort_order) VALUES
('Ná»™i tháº¥t','Ná»™i tháº¥t',10),
('BÃ n','Ná»™i tháº¥t',20),
('Gháº¿','Ná»™i tháº¥t',30),
('Tá»§','Ná»™i tháº¥t',40),
('Ká»‡','Ná»™i tháº¥t',50),
('Thiáº¿t bá»‹ Ä‘iá»‡n','Thiáº¿t bá»‹ Ä‘iá»‡n',60),
('Quáº¡t','Thiáº¿t bá»‹ Ä‘iá»‡n',70),
('Äiá»u hÃ²a','Thiáº¿t bá»‹ Ä‘iá»‡n',80),
('ÄÃ¨n','Thiáº¿t bá»‹ Ä‘iá»‡n',90),
('BÃ¬nh nÃ³ng láº¡nh','Thiáº¿t bá»‹ Ä‘iá»‡n',100),
('Thiáº¿t bá»‹ Ä‘iá»‡n tá»­','Thiáº¿t bá»‹ Ä‘iá»‡n tá»­',105),
('Äiá»‡n tá»­','Thiáº¿t bá»‹ Ä‘iá»‡n tá»­',110),
('MÃ¡y tÃ­nh','Thiáº¿t bá»‹ Ä‘iá»‡n tá»­',120),
('MÃ¡y in','Thiáº¿t bá»‹ Ä‘iá»‡n tá»­',130),
('MÃ¡y chiáº¿u','Thiáº¿t bá»‹ Ä‘iá»‡n tá»­',140),
('Loa','Thiáº¿t bá»‹ Ä‘iá»‡n tá»­',150),
('Amply','Thiáº¿t bá»‹ Ä‘iá»‡n tá»­',160),
('Micro','Thiáº¿t bá»‹ Ä‘iá»‡n tá»­',170),
('Camera','Thiáº¿t bá»‹ Ä‘iá»‡n tá»­',180),
('Thiáº¿t bá»‹ PCCC','Thiáº¿t bá»‹ PCCC',185),
('PCCC','Thiáº¿t bá»‹ PCCC',190),
('BÃ¬nh chá»¯a chÃ¡y','Thiáº¿t bá»‹ PCCC',200),
('Tá»§ PCCC','Thiáº¿t bá»‹ PCCC',210),
('ChuÃ´ng bÃ¡o chÃ¡y','Thiáº¿t bá»‹ PCCC',220),
('Thiáº¿t bá»‹ khÃ¡c','Thiáº¿t bá»‹ khÃ¡c',230),
('Dá»¥ng cá»¥ vá»‡ sinh','Thiáº¿t bá»‹ khÃ¡c',240),
('Thiáº¿t bá»‹ thá»ƒ thao','Thiáº¿t bá»‹ khÃ¡c',250),
('Thiáº¿t bá»‹ y táº¿','Thiáº¿t bá»‹ khÃ¡c',260),
('Thiáº¿t bá»‹ vÄƒn phÃ²ng','Thiáº¿t bá»‹ khÃ¡c',270)
ON DUPLICATE KEY UPDATE parent_name=VALUES(parent_name), sort_order=VALUES(sort_order), is_active=1;
