CREATE TABLE IF NOT EXISTS `household_business_catalogs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `catalog_type` VARCHAR(50) NOT NULL,
  `value` VARCHAR(150) NOT NULL,
  `label` VARCHAR(150) NOT NULL,
  `sort_order` INT UNSIGNED NOT NULL DEFAULT 0,
  `status` ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hb_catalog` (`catalog_type`, `value`),
  KEY `idx_hb_catalog_type` (`catalog_type`, `status`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `household_business`
  ADD COLUMN `economic_type` VARCHAR(120) NULL AFTER `business_type`,
  ADD COLUMN `main_products` TEXT NULL AFTER `economic_type`,
  ADD COLUMN `business_scale` VARCHAR(120) NULL AFTER `main_products`,
  ADD COLUMN `is_ocop` TINYINT(1) NOT NULL DEFAULT 0 AFTER `business_scale`,
  ADD COLUMN `ocop_product` VARCHAR(255) NULL AFTER `is_ocop`,
  ADD COLUMN `ocop_star` TINYINT UNSIGNED NULL AFTER `ocop_product`,
  ADD COLUMN `food_safety_certified` TINYINT(1) NOT NULL DEFAULT 0 AFTER `ocop_star`,
  ADD COLUMN `food_safety_certificate_no` VARCHAR(120) NULL AFTER `food_safety_certified`,
  ADD COLUMN `food_safety_expired_date` DATE NULL AFTER `food_safety_certificate_no`,
  ADD COLUMN `social_insurance` TINYINT(1) NOT NULL DEFAULT 0 AFTER `food_safety_expired_date`,
  ADD COLUMN `insured_workers` INT UNSIGNED NOT NULL DEFAULT 0 AFTER `social_insurance`;

CREATE TABLE IF NOT EXISTS `household_business_files` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `household_business_id` BIGINT UNSIGNED NOT NULL,
  `file_kind` ENUM('IMAGE','DOCUMENT') NOT NULL,
  `category` VARCHAR(120) NOT NULL,
  `original_name` VARCHAR(255) NOT NULL,
  `stored_name` VARCHAR(255) NOT NULL,
  `file_path` VARCHAR(500) NOT NULL,
  `mime_type` VARCHAR(120) NOT NULL,
  `file_size` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `status` ENUM('ACTIVE','DELETED') NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NULL,
  `deleted_at` DATETIME NULL,
  `deleted_by` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  KEY `idx_hb_files_business` (`household_business_id`, `status`, `file_kind`),
  KEY `idx_hb_files_category` (`category`),
  CONSTRAINT `fk_hb_files_business` FOREIGN KEY (`household_business_id`) REFERENCES `household_business` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hb_files_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hb_files_deleted_by` FOREIGN KEY (`deleted_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO `household_business_catalogs` (`catalog_type`, `value`, `label`, `sort_order`) VALUES
('economic_type','Sản xuất nông nghiệp','Sản xuất nông nghiệp',1),
('economic_type','Trồng trọt','Trồng trọt',2),
('economic_type','Chăn nuôi','Chăn nuôi',3),
('economic_type','Nuôi trồng thủy sản','Nuôi trồng thủy sản',4),
('economic_type','Lâm nghiệp','Lâm nghiệp',5),
('economic_type','Tiểu thủ công nghiệp','Tiểu thủ công nghiệp',6),
('economic_type','Thương mại','Thương mại',7),
('economic_type','Dịch vụ','Dịch vụ',8),
('economic_type','Xây dựng','Xây dựng',9),
('economic_type','Vận tải','Vận tải',10),
('economic_type','Chế biến thực phẩm','Chế biến thực phẩm',11),
('economic_type','Kinh doanh online','Kinh doanh online',12),
('economic_type','Khác','Khác',13),
('main_product','Lúa','Lúa',1),
('main_product','Rau','Rau',2),
('main_product','Hoa','Hoa',3),
('main_product','Cây ăn quả','Cây ăn quả',4),
('main_product','Gia súc','Gia súc',5),
('main_product','Gia cầm','Gia cầm',6),
('main_product','Thủy sản','Thủy sản',7),
('main_product','Gỗ','Gỗ',8),
('main_product','May mặc','May mặc',9),
('main_product','Tạp hóa','Tạp hóa',10),
('main_product','Nhà hàng','Nhà hàng',11),
('main_product','Dịch vụ','Dịch vụ',12),
('main_product','Khác','Khác',13),
('business_scale','Hộ cá thể','Hộ cá thể',1),
('business_scale','Tổ hợp tác','Tổ hợp tác',2),
('business_scale','Hợp tác xã','Hợp tác xã',3),
('business_scale','Doanh nghiệp tư nhân','Doanh nghiệp tư nhân',4),
('business_scale','Công ty TNHH','Công ty TNHH',5),
('business_scale','Công ty cổ phần','Công ty cổ phần',6),
('business_scale','Khác','Khác',7),
('image_category','Mặt tiền','Mặt tiền',1),
('image_category','Khu sản xuất','Khu sản xuất',2),
('image_category','Nhà xưởng','Nhà xưởng',3),
('image_category','Máy móc','Máy móc',4),
('image_category','Kho hàng','Kho hàng',5),
('image_category','Biển hiệu','Biển hiệu',6),
('image_category','Khác','Khác',7),
('document_category','Giấy phép kinh doanh','Giấy phép kinh doanh',1),
('document_category','Mã số thuế','Mã số thuế',2),
('document_category','Giấy chứng nhận ATTP','Giấy chứng nhận ATTP',3),
('document_category','Chứng nhận OCOP','Chứng nhận OCOP',4),
('document_category','VietGAP','VietGAP',5),
('document_category','GlobalGAP','GlobalGAP',6),
('document_category','Hồ sơ khác','Hồ sơ khác',7),
('ocop_star','3 sao','3 sao',3),
('ocop_star','4 sao','4 sao',4),
('ocop_star','5 sao','5 sao',5);
