CREATE TABLE IF NOT EXISTS `household_business_catalogs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `catalog_type` VARCHAR(50) NOT NULL,
  `value` VARCHAR(150) NOT NULL,
  `label` VARCHAR(150) NOT NULL,
  `sort_order` INT UNSIGNED NOT NULL DEFAULT 0,
  `status` ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hb_catalog` (`catalog_type`, `value`),
  KEY `idx_hb_catalog_type` (`catalog_type`, `status`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `household_business`
  ADD COLUMN `economic_type` VARCHAR(120) NULL AFTER `business_type`,
  ADD COLUMN `main_products` TEXT NULL AFTER `economic_type`,
  ADD COLUMN `business_scale` VARCHAR(120) NULL AFTER `main_products`,
  ADD COLUMN `is_ocop` TINYINT(1) NOT NULL DEFAULT 0 AFTER `business_scale`,
  ADD COLUMN `ocop_product` VARCHAR(255) NULL AFTER `is_ocop`,
  ADD COLUMN `ocop_star` TINYINT UNSIGNED NULL AFTER `ocop_product`,
  ADD COLUMN `food_safety_certified` TINYINT(1) NOT NULL DEFAULT 0 AFTER `ocop_star`,
  ADD COLUMN `food_safety_certificate_no` VARCHAR(120) NULL AFTER `food_safety_certified`,
  ADD COLUMN `food_safety_expired_date` DATE NULL AFTER `food_safety_certificate_no`,
  ADD COLUMN `social_insurance` TINYINT(1) NOT NULL DEFAULT 0 AFTER `food_safety_expired_date`,
  ADD COLUMN `insured_workers` INT UNSIGNED NOT NULL DEFAULT 0 AFTER `social_insurance`;

CREATE TABLE IF NOT EXISTS `household_business_files` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `household_business_id` BIGINT UNSIGNED NOT NULL,
  `file_kind` ENUM('IMAGE','DOCUMENT') NOT NULL,
  `category` VARCHAR(120) NOT NULL,
  `original_name` VARCHAR(255) NOT NULL,
  `stored_name` VARCHAR(255) NOT NULL,
  `file_path` VARCHAR(500) NOT NULL,
  `mime_type` VARCHAR(120) NOT NULL,
  `file_size` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `status` ENUM('ACTIVE','DELETED') NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` BIGINT UNSIGNED NULL,
  `deleted_at` DATETIME NULL,
  `deleted_by` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  KEY `idx_hb_files_business` (`household_business_id`, `status`, `file_kind`),
  KEY `idx_hb_files_category` (`category`),
  CONSTRAINT `fk_hb_files_business` FOREIGN KEY (`household_business_id`) REFERENCES `household_business` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hb_files_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hb_files_deleted_by` FOREIGN KEY (`deleted_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO `household_business_catalogs` (`catalog_type`, `value`, `label`, `sort_order`) VALUES
('economic_type','Sáº£n xuáº¥t nÃ´ng nghiá»‡p','Sáº£n xuáº¥t nÃ´ng nghiá»‡p',1),
('economic_type','Trá»“ng trá»t','Trá»“ng trá»t',2),
('economic_type','ChÄƒn nuÃ´i','ChÄƒn nuÃ´i',3),
('economic_type','NuÃ´i trá»“ng thá»§y sáº£n','NuÃ´i trá»“ng thá»§y sáº£n',4),
('economic_type','LÃ¢m nghiá»‡p','LÃ¢m nghiá»‡p',5),
('economic_type','Tiá»ƒu thá»§ cÃ´ng nghiá»‡p','Tiá»ƒu thá»§ cÃ´ng nghiá»‡p',6),
('economic_type','ThÆ°Æ¡ng máº¡i','ThÆ°Æ¡ng máº¡i',7),
('economic_type','Dá»‹ch vá»¥','Dá»‹ch vá»¥',8),
('economic_type','XÃ¢y dá»±ng','XÃ¢y dá»±ng',9),
('economic_type','Váº­n táº£i','Váº­n táº£i',10),
('economic_type','Cháº¿ biáº¿n thá»±c pháº©m','Cháº¿ biáº¿n thá»±c pháº©m',11),
('economic_type','Kinh doanh online','Kinh doanh online',12),
('economic_type','KhÃ¡c','KhÃ¡c',13),
('main_product','LÃºa','LÃºa',1),
('main_product','Rau','Rau',2),
('main_product','Hoa','Hoa',3),
('main_product','CÃ¢y Äƒn quáº£','CÃ¢y Äƒn quáº£',4),
('main_product','Gia sÃºc','Gia sÃºc',5),
('main_product','Gia cáº§m','Gia cáº§m',6),
('main_product','Thá»§y sáº£n','Thá»§y sáº£n',7),
('main_product','Gá»—','Gá»—',8),
('main_product','May máº·c','May máº·c',9),
('main_product','Táº¡p hÃ³a','Táº¡p hÃ³a',10),
('main_product','NhÃ  hÃ ng','NhÃ  hÃ ng',11),
('main_product','Dá»‹ch vá»¥','Dá»‹ch vá»¥',12),
('main_product','KhÃ¡c','KhÃ¡c',13),
('business_scale','Há»™ cÃ¡ thá»ƒ','Há»™ cÃ¡ thá»ƒ',1),
('business_scale','Tá»• há»£p tÃ¡c','Tá»• há»£p tÃ¡c',2),
('business_scale','Há»£p tÃ¡c xÃ£','Há»£p tÃ¡c xÃ£',3),
('business_scale','Doanh nghiá»‡p tÆ° nhÃ¢n','Doanh nghiá»‡p tÆ° nhÃ¢n',4),
('business_scale','CÃ´ng ty TNHH','CÃ´ng ty TNHH',5),
('business_scale','CÃ´ng ty cá»• pháº§n','CÃ´ng ty cá»• pháº§n',6),
('business_scale','KhÃ¡c','KhÃ¡c',7),
('image_category','Máº·t tiá»n','Máº·t tiá»n',1),
('image_category','Khu sáº£n xuáº¥t','Khu sáº£n xuáº¥t',2),
('image_category','NhÃ  xÆ°á»Ÿng','NhÃ  xÆ°á»Ÿng',3),
('image_category','MÃ¡y mÃ³c','MÃ¡y mÃ³c',4),
('image_category','Kho hÃ ng','Kho hÃ ng',5),
('image_category','Biá»ƒn hiá»‡u','Biá»ƒn hiá»‡u',6),
('image_category','KhÃ¡c','KhÃ¡c',7),
('document_category','Giáº¥y phÃ©p kinh doanh','Giáº¥y phÃ©p kinh doanh',1),
('document_category','MÃ£ sá»‘ thuáº¿','MÃ£ sá»‘ thuáº¿',2),
('document_category','Giáº¥y chá»©ng nháº­n ATTP','Giáº¥y chá»©ng nháº­n ATTP',3),
('document_category','Chá»©ng nháº­n OCOP','Chá»©ng nháº­n OCOP',4),
('document_category','VietGAP','VietGAP',5),
('document_category','GlobalGAP','GlobalGAP',6),
('document_category','Há»“ sÆ¡ khÃ¡c','Há»“ sÆ¡ khÃ¡c',7),
('ocop_star','3 sao','3 sao',3),
('ocop_star','4 sao','4 sao',4),
('ocop_star','5 sao','5 sao',5);
