<?php

return [
    'lookahead_days' => \App\Policies\AgePolicy::UPCOMING_POLICY_LOOKAHEAD_DAYS,
    'alerts' => [
        'age_70' => [
            'label' => "\u{0110}\u{1EE7} " . \App\Policies\InsurancePolicy::DEFAULT_AGE . " tu\u{1ED5}i",
            'age' => \App\Policies\InsurancePolicy::DEFAULT_AGE,
            'type' => 'reached',
            'purpose' => "Rà soát chính sách BHYT",
            'exclude_if_field' => 'health_insurance_group',
            'exclude_if_values' => ["Ng\u{01B0}\u{1EDD}i cao tu\u{1ED5}i", "\u{0110}\u{1ED1}i t\u{01B0}\u{1EE3}ng kh\u{00E1}c"],
            'exclude_if_prefixes' => ["Ng\u{01B0}\u{1EDD}i cao tu\u{1ED5}i", "\u{0110}\u{1ED1}i t\u{01B0}\u{1EE3}ng kh\u{00E1}c"],
            'message' => "C\u{00F3} %d ng\u{01B0}\u{1EDD}i t\u{1EEB} " . \App\Policies\InsurancePolicy::DEFAULT_AGE . " tu\u{1ED5}i tr\u{1EDF} l\u{00EA}n ch\u{01B0}a chuy\u{1EC3}n b\u{1EA3}o hi\u{1EC3}m ng\u{01B0}\u{1EDD}i cao tu\u{1ED5}i.",
        ],
        'age_75' => [
            'label' => "\u{0110}\u{1EE7} " . \App\Config\CitizenPolicyDefaults::SOCIAL_ALLOWANCE_DEFAULT_AGE . " tu\u{1ED5}i",
            'age' => \App\Config\CitizenPolicyDefaults::SOCIAL_ALLOWANCE_DEFAULT_AGE,
            'type' => 'reached',
            'purpose' => "R\u{00E0} so\u{00E1}t tr\u{1EE3} c\u{1EA5}p x\u{00E3} h\u{1ED9}i",
            'exclude_if_flag' => 'social_assistance',
            'message' => "C\u{00F3} %d ng\u{01B0}\u{1EDD}i t\u{1EEB} " . \App\Config\CitizenPolicyDefaults::SOCIAL_ALLOWANCE_DEFAULT_AGE . " tu\u{1ED5}i tr\u{1EDF} l\u{00EA}n ch\u{01B0}a h\u{01B0}\u{1EDF}ng tr\u{1EE3} c\u{1EA5}p c\u{1EA7}n r\u{00E0} so\u{00E1}t.",
        ],
        'age_70_health_insurance_effective' => [
            'label' => "70+ c\u{00F3} BHYT",
            'age' => \App\Policies\InsurancePolicy::DEFAULT_AGE,
            'type' => 'reached',
            'purpose' => "Danh s\u{00E1}ch ng\u{01B0}\u{1EDD}i t\u{1EEB} 70 tu\u{1ED5}i tr\u{1EDF} l\u{00EA}n c\u{00F3} BHYT hi\u{1EC7}u l\u{1EF1}c.",
            'message' => "C\u{00F3} %d ng\u{01B0}\u{1EDD}i t\u{1EEB} 70 tu\u{1ED5}i tr\u{1EDF} l\u{00EA}n c\u{00F3} BHYT hi\u{1EC7}u l\u{1EF1}c.",
            'summary' => false,
        ],
        'age_70_health_insurance_missing' => [
            'label' => "70+ c\u{1EA7}n r\u{00E0} so\u{00E1}t BHYT",
            'age' => \App\Policies\InsurancePolicy::DEFAULT_AGE,
            'type' => 'reached',
            'purpose' => "Ch\u{01B0}a ghi nh\u{1EAD}n BHYT hi\u{1EC7}u l\u{1EF1}c trong h\u{1EC7} th\u{1ED1}ng.",
            'subtitle' => "Danh s\u{00E1}ch ph\u{1EE5}c v\u{1EE5} r\u{00E0} so\u{00E1}t d\u{1EEF} li\u{1EC7}u BHYT, kh\u{00F4}ng t\u{1EF1} k\u{1EBF}t lu\u{1EAD}n ng\u{01B0}\u{1EDD}i d\u{00E2}n ch\u{01B0}a c\u{00F3} quy\u{1EC1}n l\u{1EE3}i.",
            'message' => "C\u{00F3} %d ng\u{01B0}\u{1EDD}i t\u{1EEB} 70 tu\u{1ED5}i tr\u{1EDF} l\u{00EA}n c\u{1EA7}n r\u{00E0} so\u{00E1}t BHYT.",
            'summary' => false,
        ],
        'age_75_social_assistance_legacy_missing_record' => [
            'label' => "Ng\u{01B0}\u{1EDD}i t\u{1EEB} 75 tu\u{1ED5}i c\u{1EA7}n r\u{00E0} so\u{00E1}t BTXH",
            'age' => \App\Policies\AgePolicy::SOCIAL_ALLOWANCE_DEFAULT_AGE,
            'type' => 'reached',
            'purpose' => "Danh s\u{00E1}ch ng\u{01B0}\u{1EDD}i t\u{1EEB} 75 tu\u{1ED5}i tr\u{1EDF} l\u{00EA}n ch\u{01B0}a ho\u{00E0}n th\u{00E0}nh r\u{00E0} so\u{00E1}t t\u{00EC}nh tr\u{1EA1}ng h\u{01B0}\u{1EDF}ng BTXH.",
            'subtitle' => "Danh s\u{00E1}ch ng\u{01B0}\u{1EDD}i t\u{1EEB} 75 tu\u{1ED5}i tr\u{1EDF} l\u{00EA}n ch\u{01B0}a ho\u{00E0}n th\u{00E0}nh r\u{00E0} so\u{00E1}t t\u{00EC}nh tr\u{1EA1}ng h\u{01B0}\u{1EDF}ng BTXH.",
            'message' => "C\u{00F2}n %d ng\u{01B0}\u{1EDD}i t\u{1EEB} 75 tu\u{1ED5}i tr\u{1EDF} l\u{00EA}n c\u{1EA7}n r\u{00E0} so\u{00E1}t BTXH.",
        ],
        'age_75_social_assistance_no_legacy_no_record' => [
            'label' => "75+ ch\u{01B0}a c\u{00F3} d\u{1EEF} li\u{1EC7}u BTXH",
            'age' => \App\Policies\AgePolicy::SOCIAL_ALLOWANCE_DEFAULT_AGE,
            'type' => 'reached',
            'purpose' => "Kh\u{00F4}ng c\u{00F3} \u{0111}\u{00E1}nh d\u{1EA5}u c\u{0169} v\u{00E0} ch\u{01B0}a c\u{00F3} th\u{00F4}ng tin BTXH hi\u{1EC7}n h\u{00E0}nh.",
            'message' => "C\u{00F3} %d ng\u{01B0}\u{1EDD}i t\u{1EEB} 75 tu\u{1ED5}i tr\u{1EDF} l\u{00EA}n ch\u{01B0}a c\u{00F3} d\u{1EEF} li\u{1EC7}u BTXH trong h\u{1EC7} th\u{1ED1}ng.",
            'summary' => false,
        ],
        'age_75_social_assistance_inactive_record' => [
            'label' => "75+ c\u{00F3} h\u{1ED3} s\u{01A1} BTXH kh\u{00F4}ng hi\u{1EC7}n h\u{00E0}nh",
            'age' => \App\Policies\AgePolicy::SOCIAL_ALLOWANCE_DEFAULT_AGE,
            'type' => 'reached',
            'purpose' => "C\u{00F3} h\u{1ED3} s\u{01A1} BTXH nh\u{01B0}ng kh\u{00F4}ng thu\u{1ED9}c tr\u{1EA1}ng th\u{00E1}i \u{0111}ang h\u{01B0}\u{1EDF}ng.",
            'message' => "C\u{00F3} %d ng\u{01B0}\u{1EDD}i t\u{1EEB} 75 tu\u{1ED5}i tr\u{1EDF} l\u{00EA}n c\u{00F3} h\u{1ED3} s\u{01A1} BTXH kh\u{00F4}ng hi\u{1EC7}n h\u{00E0}nh.",
            'summary' => false,
        ],
        'upcoming_70' => [
            'label' => "S\u{1EAF}p \u{0111}\u{1EE7} " . \App\Policies\InsurancePolicy::DEFAULT_AGE . " tu\u{1ED5}i",
            'age' => \App\Policies\InsurancePolicy::DEFAULT_AGE,
            'type' => 'upcoming',
            'purpose' => "S\u{1EAF}p \u{0111}\u{1EBF}n tu\u{1ED5}i chuy\u{1EC3}n b\u{1EA3}o hi\u{1EC3}m ng\u{01B0}\u{1EDD}i cao tu\u{1ED5}i",
            'exclude_if_field' => 'health_insurance_group',
            'exclude_if_values' => ["Ng\u{01B0}\u{1EDD}i cao tu\u{1ED5}i", "\u{0110}\u{1ED1}i t\u{01B0}\u{1EE3}ng kh\u{00E1}c"],
            'exclude_if_prefixes' => ["Ng\u{01B0}\u{1EDD}i cao tu\u{1ED5}i", "\u{0110}\u{1ED1}i t\u{01B0}\u{1EE3}ng kh\u{00E1}c"],
            'message' => "C\u{00F3} %d ng\u{01B0}\u{1EDD}i s\u{1EBD} \u{0111}\u{1EE7} " . \App\Policies\InsurancePolicy::DEFAULT_AGE . " tu\u{1ED5}i trong v\u{00F2}ng " . \App\Policies\AgePolicy::UPCOMING_POLICY_LOOKAHEAD_DAYS . " ng\u{00E0}y ch\u{01B0}a chuy\u{1EC3}n b\u{1EA3}o hi\u{1EC3}m ng\u{01B0}\u{1EDD}i cao tu\u{1ED5}i.",
        ],
        'upcoming_75' => [
            'label' => "S\u{1EAF}p \u{0111}\u{1EE7} " . \App\Config\CitizenPolicyDefaults::SOCIAL_ALLOWANCE_DEFAULT_AGE . " tu\u{1ED5}i",
            'age' => \App\Config\CitizenPolicyDefaults::SOCIAL_ALLOWANCE_DEFAULT_AGE,
            'type' => 'upcoming',
            'purpose' => "Sắp đến tuổi rà soát trợ cấp",
            'exclude_if_flag' => 'social_assistance',
            'message' => "C\u{00F3} %d ng\u{01B0}\u{1EDD}i ch\u{01B0}a h\u{01B0}\u{1EDF}ng tr\u{1EE3} c\u{1EA5}p s\u{1EBD} \u{0111}\u{1EE7} " . \App\Config\CitizenPolicyDefaults::SOCIAL_ALLOWANCE_DEFAULT_AGE . " tu\u{1ED5}i trong v\u{00F2}ng " . \App\Policies\AgePolicy::UPCOMING_POLICY_LOOKAHEAD_DAYS . " ng\u{00E0}y.",
        ],
    ],
];
