<?php

namespace App\Models;

use App\Core\BaseModel;
use PDO;

final class Backup extends BaseModel
{
    public function createSqlDump(int $userId): array
    {
        $tables = $this->fetchAll("SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'");
        $body = "SET NAMES utf8mb4;\nSET FOREIGN_KEY_CHECKS=0;\n\n";
        foreach ($tables as $row) {
            $table = array_values($row)[0];
            $safeTable = str_replace('`', '``', $table);
            $create = $this->fetchOne('SHOW CREATE TABLE `' . $safeTable . '`');
            $body .= "DROP TABLE IF EXISTS `$safeTable`;\n" . ($create['Create Table'] ?? array_values($create)[1]) . ";\n\n";
            $records = $this->fetchAll('SELECT * FROM `' . $safeTable . '`');
            foreach ($records as $record) {
                $columns = array_map(fn($col) => '`' . str_replace('`', '``', $col) . '`', array_keys($record));
                $values = array_map(fn($value) => $value === null ? 'NULL' : $this->db->quote((string) $value, PDO::PARAM_STR), array_values($record));
                $body .= 'INSERT INTO `' . $safeTable . '` (' . implode(',', $columns) . ') VALUES (' . implode(',', $values) . ");\n";
            }
            $body .= "\n";
        }
        $body .= "SET FOREIGN_KEY_CHECKS=1;\n";
        $sql = "-- Quan Ly Nhan Khau Thon 09 backup\n-- Created at: " . date('c') . "\n-- Signature: " . $this->backupSignature($body) . "\n" . $body;
        $fileName = 'Backup_' . date('Ymd_Hi') . '.sql';
        $checksum = hash('sha256', $sql);
        $this->insert('INSERT INTO backups (file_name, file_path, file_size, checksum, status, created_by) VALUES (:file_name,:file_path,:file_size,:checksum,"SUCCESS",:user)', ['file_name' => $fileName, 'file_path' => 'download://' . $fileName, 'file_size' => strlen($sql), 'checksum' => $checksum, 'user' => $userId]);
        return ['fileName' => $fileName, 'content' => $sql, 'size' => strlen($sql), 'checksum' => $checksum];
    }

    public function restoreSql(string $sql, int $userId): array
    {
        $sql = trim($sql);
        if ($sql === '') throw new \RuntimeException('Restore SQL content is empty');
        $this->validateRestoreSql($sql);
        $statements = array_filter(array_map('trim', preg_split('/;\s*\n/', $sql)));
        $count = 0;
        $this->db->beginTransaction();
        try {
            foreach ($statements as $statement) {
                if ($statement === '' || str_starts_with($statement, '--')) continue;
                $this->db->exec($statement);
                $count++;
            }
            $this->db->commit();
        } catch (\Throwable $e) {
            $this->db->rollBack();
            throw $e;
        }
        $fileName = 'Restore_' . date('Ymd_Hi') . '.sql';
        $checksum = hash('sha256', $sql);
        $this->insert('INSERT INTO backups (file_name, file_path, file_size, checksum, status, created_by, restored_at, restored_by) VALUES (:file_name,:file_path,:file_size,:checksum,"RESTORED",:created_by,NOW(),:restored_by)', ['file_name' => $fileName, 'file_path' => 'restore://inline', 'file_size' => strlen($sql), 'checksum' => $checksum, 'created_by' => $userId, 'restored_by' => $userId]);
        return ['statements' => $count, 'checksum' => $checksum];
    }

    private function validateRestoreSql(string $sql): void
    {
        if (!str_contains($sql, '-- Quan Ly Nhan Khau Thon 09 backup')) {
            throw new \RuntimeException('Restore SQL must be generated by this application');
        }
        if (!$this->verifyBackupSignature($sql)) {
            throw new \RuntimeException('Restore SQL signature is invalid');
        }

        $blocked = '/\b(LOAD_FILE|INTO\s+OUTFILE|INTO\s+DUMPFILE|CREATE\s+USER|ALTER\s+USER|GRANT|REVOKE|DROP\s+DATABASE|CREATE\s+DATABASE)\b/i';
        if (preg_match($blocked, $sql) === 1) {
            throw new \RuntimeException('Restore SQL contains unsupported privileged statements');
        }
    }

    private function backupSignature(string $body): string
    {
        $config = require BASE_PATH . '/config/app.php';
        return hash_hmac('sha256', rtrim($body), (string) ($config['app_key'] ?? ''));
    }

    private function verifyBackupSignature(string $sql): bool
    {
        if (!preg_match('/^-- Signature:\s*([a-f0-9]{64})$/mi', $sql, $matches)) {
            return false;
        }
        $body = preg_replace('/^-- Quan Ly Nhan Khau Thon 09 backup\r?\n-- Created at:.*\r?\n-- Signature:\s*[a-f0-9]{64}\r?\n/mi', '', $sql, 1);
        return is_string($body) && hash_equals(strtolower($matches[1]), $this->backupSignature($body));
    }

    public function paginate(array $filters = []): array
    {
        [$page, $pageSize, $offset] = $this->page((int) ($filters['page'] ?? 1), (int) ($filters['pageSize'] ?? 20));
        $total = (int) $this->fetchOne('SELECT COUNT(*) AS total FROM backups')['total'];
        $items = $this->fetchAll("SELECT b.*, u.email AS created_by_email FROM backups b LEFT JOIN users u ON u.id=b.created_by ORDER BY b.created_at DESC LIMIT $pageSize OFFSET $offset");
        return $this->paginated($items, $page, $pageSize, $total);
    }
}
